version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_mongo_username
      MONGO_INITDB_ROOT_PASSWORD: your_mongo_password
    volumes:
      - mongodb_data:/data/db

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
