version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: contest_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongodb_data:/data/db

  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8010:8010"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
