version: '3'

services:
  contest_constructor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          APP_PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    env_file:
      - .env